name: CI/CD - Deploy Application to GCP VM

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  # -------------------------------
  # Continuous Integration
  # -------------------------------
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-app-repo/${IMAGE_NAME}:${IMAGE_TAG}"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

  # -------------------------------
  # Continuous Deployment
  # -------------------------------
  deploy-to-vm:
    needs: build-and-push
    runs-on: self-hosted  # Your GCP VM registered as GitHub runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Pull and run Docker container
        env:
          IMAGE: ${{ env.IMAGE }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }} # Add this in GitHub secrets
        run: |
          echo "Deploying image: $IMAGE"
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d -p 5000:5000 --name $IMAGE_NAME \
            -e MONGODB_URL="$MONGODB_URL" \
            $IMAGE
