name: Deploy Application Docker Image to GCP VM

on:
  push:
    branches: [main]

jobs:
  Continuous:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URI: ${{ steps.build-image.outputs.image_uri }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Display authenticated account
        run: gcloud auth list

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image to Artifact Registry
        id: build-image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPO: ${{ secrets.GCP_ARTIFACT_REPO }}
          IMAGE: app
        run: |
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:latest"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  Continuous-Deployment:
    needs: Continuous
    runs-on: self-hosted   # This runs on your GCP VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Pull and run Docker container on VM
        env:
          IMAGE_URI: ${{ needs.Continuous.outputs.IMAGE_URI }}
        run: |
          docker pull "$IMAGE_URI"
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 5000:5000 \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            "$IMAGE_URI"